// react-template/src/components/ModalEditarEmpresa.tsx
import React, { useState, useEffect } from 'react';
import { Empresa, EmpresaEstado } from '../types';

interface ModalEditarEmpresaProps {
  isOpen: boolean;
  empresa: Empresa | null;
  onClose: () => void;
  onUpdate: (empresaId: string, updatedData: Partial<Empresa>) => void;
}

export const ModalEditarEmpresa: React.FC<ModalEditarEmpresaProps> = ({
  isOpen,
  empresa,
  onClose,
  onUpdate
}) => {
  const [nombre, setNombre] = useState('');
  const [rif, setRif] = useState('');
  const [sector, setSector] = useState('');
  const [estado, setEstado] = useState<EmpresaEstado>('ACTIVO');
  const [direccionFiscal, setDireccionFiscal] = useState('');
  const [telefono, setTelefono] = useState('');
  const [email, setEmail] = useState('');

  useEffect(() => {
    if (empresa) {
      setNombre(empresa.nombre);
      setRif(empresa.rif);
      setSector(empresa.sector);
      setEstado(empresa.estado);
      setDireccionFiscal(empresa.direccionFiscal || '');
      setTelefono(empresa.telefono || '');
      setEmail(empresa.email || '');
    }
  }, [empresa]);

  if (!isOpen || !empresa) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onUpdate(empresa.id, {
      nombre: nombre.trim(),
      rif: rif.trim(),
      sector,
      estado,
      direccionFiscal: direccionFiscal.trim(),
      telefono: telefono.trim(),
      email: email.trim()
    });
    onClose();
  };

  return (
    <div className="fixed inset-0 bg-[#0F172A]/40 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-[520px] border border-[#E2E8F0] overflow-hidden flex flex-col max-h-[90vh] animate-in fade-in zoom-in-95 duration-150">
        <div className="px-6 py-3.5 border-b border-[#E2E8F0] flex justify-between items-center bg-[#F8FAFC]">
          <div>
            <h3 className="text-[16px] font-bold text-[#0b1c30]">Editar Empresa</h3>
            <p className="text-[11px] text-slate-500 font-mono">Código: {empresa.codigo}</p>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-700 transition-colors p-1 rounded hover:bg-slate-200/50"
          >
            <span className="material-symbols-outlined text-[18px]">close</span>
          </button>
        </div>

        <div className="p-6 overflow-y-auto flex-1">
          <form id="form-editar-empresa" onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-[12px] font-semibold text-slate-700 mb-1">
                Razón Social
              </label>
              <input
                value={nombre}
                onChange={(e) => setNombre(e.target.value)}
                className="w-full h-[34px] px-3 text-[13px] border border-slate-300 rounded focus:border-[#004ac6] focus:ring-2 focus:ring-blue-500/20 outline-none bg-white text-slate-900"
                required
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-[12px] font-semibold text-slate-700 mb-1">
                  RIF / NIT
                </label>
                <input
                  value={rif}
                  onChange={(e) => setRif(e.target.value)}
                  className="w-full h-[34px] px-3 text-[13px] border border-slate-300 rounded focus:border-[#004ac6] focus:ring-2 focus:ring-blue-500/20 outline-none bg-white text-slate-900 font-mono"
                  required
                />
              </div>

              <div>
                <label className="block text-[12px] font-semibold text-slate-700 mb-1">
                  Estado Operativo
                </label>
                <select
                  value={estado}
                  onChange={(e) => setEstado(e.target.value as EmpresaEstado)}
                  className="w-full h-[34px] px-3 text-[13px] border border-slate-300 rounded focus:border-[#004ac6] focus:ring-2 focus:ring-blue-500/20 outline-none bg-white text-slate-900 cursor-pointer font-semibold"
                >
                  <option value="ACTIVO">ACTIVO (Operativo)</option>
                  <option value="SUSPENDIDO">SUSPENDIDO (Pausa)</option>
                  <option value="BAJA">BAJA (Inactivo)</option>
                </select>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-[12px] font-semibold text-slate-700 mb-1">
                  Sector Comercial
                </label>
                <select
                  value={sector}
                  onChange={(e) => setSector(e.target.value)}
                  className="w-full h-[34px] px-3 text-[13px] border border-slate-300 rounded focus:border-[#004ac6] focus:ring-2 focus:ring-blue-500/20 outline-none bg-white text-slate-900 cursor-pointer"
                >
                  <option value="Transporte">Transporte</option>
                  <option value="Retail">Retail</option>
                  <option value="Tecnología">Tecnología</option>
                  <option value="Farmacéutico">Farmacéutico</option>
                  <option value="Alimentos">Alimentos</option>
                  <option value="Manufactura">Manufactura</option>
                  <option value="Servicios">Servicios</option>
                </select>
              </div>

              <div>
                <label className="block text-[12px] font-semibold text-slate-700 mb-1">
                  Teléfono
                </label>
                <input
                  value={telefono}
                  onChange={(e) => setTelefono(e.target.value)}
                  className="w-full h-[34px] px-3 text-[13px] border border-slate-300 rounded focus:border-[#004ac6] focus:ring-2 focus:ring-blue-500/20 outline-none bg-white text-slate-900"
                />
              </div>
            </div>

            <div>
              <label className="block text-[12px] font-semibold text-slate-700 mb-1">
                Email
              </label>
              <input
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="w-full h-[34px] px-3 text-[13px] border border-slate-300 rounded focus:border-[#004ac6] focus:ring-2 focus:ring-blue-500/20 outline-none bg-white text-slate-900"
              />
            </div>

            <div>
              <label className="block text-[12px] font-semibold text-slate-700 mb-1">
                Dirección Fiscal
              </label>
              <textarea
                value={direccionFiscal}
                onChange={(e) => setDireccionFiscal(e.target.value)}
                rows={2}
                className="w-full px-3 py-1.5 text-[13px] border border-slate-300 rounded focus:border-[#004ac6] focus:ring-2 focus:ring-blue-500/20 outline-none bg-white text-slate-900 resize-none"
              />
            </div>
          </form>
        </div>

        <div className="px-6 py-3.5 border-t border-[#E2E8F0] bg-[#F8FAFC] flex justify-end gap-2">
          <button
            type="button"
            onClick={onClose}
            className="h-[32px] px-4 bg-white border border-slate-300 rounded text-slate-700 font-medium text-[12px] hover:bg-slate-50 transition-colors"
          >
            Cancelar
          </button>
          <button
            type="submit"
            form="form-editar-empresa"
            className="h-[32px] px-4 bg-[#004ac6] text-white rounded font-medium text-[12px] hover:bg-blue-700 transition-colors shadow-sm flex items-center gap-1.5"
          >
            <span className="material-symbols-outlined text-[16px]">check</span>
            Actualizar Empresa
          </button>
        </div>
      </div>
    </div>
  );
};

// src/features/empresas/components/ModalEditarEmpresa.vue
﻿<script setup lang="ts">
import { watch } from 'vue';
import { toTypedSchema } from '@vee-validate/zod';
import { useForm } from 'vee-validate';
import { crearEmpresaSchema } from '../schema/empresas.schema';
import type { EmpresaResponse, CrearEmpresaRequest } from '../dto/empresas.dto';

const props = defineProps<{
  empresa: EmpresaResponse | null;
  isLoading?: boolean;
}>();

const emit = defineEmits<{
  (e: 'close'): void;
  (e: 'actualizar', payload: CrearEmpresaRequest): void;
}>();

const { defineField, handleSubmit, errors, setValues } = useForm({
  validationSchema: toTypedSchema(crearEmpresaSchema),
});

const [ruc, rucProps] = defineField('ruc');
const [razonSocial, razonSocialProps] = defineField('razonSocial');

watch(() => props.empresa, (newVal) => {
  if (newVal) {
    setValues({
      ruc: newVal.ruc,
      razonSocial: newVal.nombre,
    });
  }
}, { immediate: true });

const onSubmit = handleSubmit((values) => {
  emit('actualizar', { ruc: values.ruc, razonSocial: values.razonSocial });
});
</script>

<template>
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm transition-opacity">
    <div class="bg-white rounded-lg shadow-xl w-full max-w-md mx-4 overflow-hidden flex flex-col max-h-[90vh]">
      <!-- Header -->
      <div class="px-5 py-4 border-b border-slate-200 flex justify-between items-center bg-slate-50">
        <h3 class="text-lg font-bold text-slate-800 flex items-center gap-2">
          <span class="material-symbols-outlined text-blue-600 text-[20px]">edit</span>
          Editar Empresa
        </h3>
        <button type="button" @click="emit('close')" class="text-slate-400 hover:text-slate-600 transition-colors cursor-pointer">
          <span class="material-symbols-outlined text-[20px]">close</span>
        </button>
      </div>
      
      <!-- Body -->
      <form @submit.prevent="onSubmit" class="p-5 space-y-4 overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] [scrollbar-width:none]">
        <div>
          <label for="rucEdit" class="block text-sm font-semibold text-slate-700 mb-1">RUC / NIT</label>
          <input 
            id="rucEdit"
            v-model="ruc"
            v-bind="rucProps"
            type="text" 
            placeholder="Ej. 10401234568" 
            class="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all text-sm"
          />
          <p v-if="errors.ruc" class="text-red-500 text-xs mt-1">{{ errors.ruc }}</p>
        </div>
        <div>
          <label for="razonSocialEdit" class="block text-sm font-semibold text-slate-700 mb-1">Razón Social</label>
          <input 
            id="razonSocialEdit"
            v-model="razonSocial"
            v-bind="razonSocialProps"
            type="text" 
            placeholder="Ej. SITFAI Technologies C.A." 
            class="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all text-sm"
          />
          <p v-if="errors.razonSocial" class="text-red-500 text-xs mt-1">{{ errors.razonSocial }}</p>
        </div>
        
        <!-- TODO: Campos inertes para futura implementación del backend -->
        <div class="opacity-60 grayscale cursor-not-allowed border-t border-dashed border-slate-200 pt-4 mt-4 space-y-4">
          <p class="text-[10px] text-slate-500 font-bold uppercase tracking-wider text-center">Campos en Desarrollo (Próximamente)</p>
          
          <div>
            <label class="block text-sm font-semibold text-slate-500 mb-1">Sector Comercial</label>
            <input disabled type="text" placeholder="Ej. Tecnología" class="w-full px-3 py-2 border border-slate-200 bg-slate-50 rounded-md text-sm" />
          </div>
          <div class="grid grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-semibold text-slate-500 mb-1">Teléfono</label>
              <input disabled type="text" placeholder="+00 00000000" class="w-full px-3 py-2 border border-slate-200 bg-slate-50 rounded-md text-sm" />
            </div>
            <div>
              <label class="block text-sm font-semibold text-slate-500 mb-1">Email</label>
              <input disabled type="email" placeholder="contacto@empresa.com" class="w-full px-3 py-2 border border-slate-200 bg-slate-50 rounded-md text-sm" />
            </div>
          </div>
          <div>
            <label class="block text-sm font-semibold text-slate-500 mb-1">Dirección Fiscal</label>
            <textarea disabled rows="2" placeholder="Dirección principal..." class="w-full px-3 py-2 border border-slate-200 bg-slate-50 rounded-md text-sm"></textarea>
          </div>
        </div>

        <!-- Actions -->
        <div class="pt-4 flex justify-end gap-2 border-t border-slate-100 mt-6">
          <button 
            type="button" 
            @click="emit('close')" 
            class="px-4 py-2 border border-slate-300 rounded-md text-sm font-semibold text-slate-700 hover:bg-slate-50 transition-colors cursor-pointer"
          >
            Cancelar
          </button>
          <button 
            type="submit" 
            :disabled="isLoading"
            class="px-4 py-2 bg-blue-600 rounded-md text-sm font-semibold text-white hover:bg-blue-700 transition-colors shadow-sm flex items-center gap-1.5 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <span v-if="isLoading" class="material-symbols-outlined text-[18px] animate-spin">sync</span>
            <span v-else class="material-symbols-outlined text-[18px]">save</span>
            {{ isLoading ? 'Guardando...' : 'Guardar' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
