// src/features/iam/components/RolesCardsTable.vue
<script setup lang="ts">
import type { RolResponse, PermisoModulo } from '../dto/iam.dto';

defineProps<{
  roles: RolResponse[];
}>();

const emit = defineEmits<{
  editar: [rol: RolResponse];
  eliminar: [id: string];
}>();

function formatDate(isoString: string): string {
  if (!isoString) return 'Desconocido';
  const date = new Date(isoString);
  return date.toLocaleDateString('es-PE', { day: '2-digit', month: 'short', year: 'numeric' });
}

function summarizePermisos(permisos?: PermisoModulo[]): string {
  if (!permisos || permisos.length === 0) return 'Sin permisos configurados';
  return permisos.map((p) => `${p.modulo}: ${p.acciones.length}`).join(' | ');
}
</script>

<template>
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
    <div
      v-for="rol in roles"
      :key="rol.id"
      class="bg-white rounded-xl border border-border shadow-sm hover:shadow-md transition-shadow flex flex-col overflow-hidden"
    >
      <!-- Header -->
      <div class="p-4 border-b border-border bg-surface-50 flex items-start justify-between">
        <div class="flex items-center space-x-3">
          <div class="h-10 w-10 rounded-lg bg-blue-100 text-blue-700 flex items-center justify-center shrink-0">
            <span class="material-symbols-outlined text-[24px]">shield</span>
          </div>
          <div>
            <h3 class="text-sm font-bold text-text-main flex items-center gap-2">
              {{ rol.nombre }}
              <span
                v-if="rol.esSistema"
                class="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold bg-amber-100 text-amber-800"
              >
                SISTEMA
              </span>
            </h3>
            <p class="text-[11px] text-text-muted font-mono mt-0.5">{{ rol.codigo }}</p>
          </div>
        </div>
        
        <!-- Actions Dropdown or simple buttons (using simple buttons for now) -->
        <div class="flex space-x-1">
          <button
            type="button"
            class="p-1.5 text-text-muted hover:text-primary rounded hover:bg-white transition-colors cursor-pointer"
            title="Editar Rol"
            @click="emit('editar', rol)"
          >
            <span class="material-symbols-outlined text-[18px]">edit</span>
          </button>
          <button
            v-if="!rol.esSistema"
            type="button"
            class="p-1.5 text-text-muted hover:text-red-600 rounded hover:bg-white transition-colors cursor-pointer"
            title="Eliminar Rol"
            @click="emit('eliminar', rol.id)"
          >
            <span class="material-symbols-outlined text-[18px]">delete</span>
          </button>
        </div>
      </div>

      <!-- Body -->
      <div class="p-4 flex-1 flex flex-col space-y-3">
        <p class="text-xs text-text-muted leading-relaxed">
          {{ rol.descripcion || 'Sin descripción.' }}
        </p>
        
        <div class="bg-surface-50 p-2.5 rounded-lg border border-border mt-auto">
          <p class="text-[10px] font-semibold text-text-muted uppercase tracking-wider mb-1">Matriz de Permisos</p>
          <p class="text-xs text-text-main font-medium">
            {{ summarizePermisos(rol.permisos) }}
          </p>
        </div>
      </div>

      <!-- Footer -->
      <div class="p-4 border-t border-border bg-surface-50 flex items-center justify-between text-xs text-text-muted">
        <div class="flex items-center space-x-1">
          <span class="material-symbols-outlined text-[16px]">group</span>
          <span class="font-medium text-text-main">{{ rol.usuariosCount }}</span>
          <span>usuarios</span>
        </div>
        <div class="flex items-center space-x-1">
          <span class="material-symbols-outlined text-[14px]">update</span>
          <span>{{ formatDate(rol.fechaActualizacion) }}</span>
        </div>
      </div>
    </div>
    
    <!-- Empty state -->
    <div v-if="!roles || roles.length === 0" class="col-span-full py-16 flex flex-col items-center justify-center text-text-muted bg-white rounded-xl border border-border shadow-sm">
      <span class="material-symbols-outlined text-[48px] mb-3 opacity-30">admin_panel_settings</span>
      <p class="font-medium text-text-main">No hay roles registrados</p>
      <p class="text-xs text-text-muted mt-1">Cree un nuevo rol para gestionar los permisos RBAC.</p>
    </div>
  </div>
</template>

// template/src/app/features/iam/ui/roles-list/roles-cards-table.component.ts
import { ChangeDetectionStrategy, Component, inject, input } from '@angular/core';
import { DatePipe } from '@angular/common';
import { Rol } from '../../../../entities/iam/models/iam.interface';
import { IamStore } from '../../store/iam.store';

@Component({
  selector: 'app-roles-cards-table',
  standalone: true,
  imports: [DatePipe],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="space-y-4">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        @for (rol of roles(); track rol.id) {
          <div class="bg-white rounded-xl border border-surface-200 shadow-sm p-5 hover:border-surface-300 transition-all flex flex-col justify-between">
            <div>
              <!-- Header Card -->
              <div class="flex items-start justify-between">
                <div class="flex items-center space-x-3">
                  <div class="h-10 w-10 rounded-lg flex items-center justify-center font-bold"
                    [class]="rol.esSistema ? 'bg-amber-100 text-amber-800' : 'bg-primary-50 text-primary-700'">
                    <span class="material-icons text-[22px]">{{ rol.esSistema ? 'verified_user' : 'shield' }}</span>
                  </div>
                  <div>
                    <div class="flex items-center space-x-2">
                      <h4 class="text-sm font-bold text-surface-900">{{ rol.nombre }}</h4>
                      @if (rol.esSistema) {
                        <span class="px-2 py-0.5 text-[10px] font-bold rounded bg-amber-100 text-amber-800 border border-amber-200">
                          SISTEMA
                        </span>
                      }
                    </div>
                    <span class="text-xs font-mono text-surface-500 uppercase">{{ rol.codigo }}</span>
                  </div>
                </div>

                <!-- Actions menu -->
                <div class="flex items-center space-x-1">
                  <button
                    type="button"
                    (click)="store.openEditRolModal(rol)"
                    class="p-1.5 text-surface-400 hover:text-primary-600 rounded-md hover:bg-surface-100 transition-colors"
                    title="Configurar Permisos del Rol">
                    <span class="material-icons text-[18px]">tune</span>
                  </button>
                  @if (!rol.esSistema) {
                    <button
                      type="button"
                      (click)="deleteRol(rol)"
                      class="p-1.5 text-surface-400 hover:text-red-600 rounded-md hover:bg-surface-100 transition-colors"
                      title="Eliminar Rol">
                      <span class="material-icons text-[18px]">delete_outline</span>
                    </button>
                  }
                </div>
              </div>

              <!-- Descripcion -->
              <p class="text-xs text-surface-600 mt-3 line-clamp-2 leading-relaxed">
                {{ rol.descripcion }}
              </p>

              <!-- Matriz de modulos incluidos -->
              <div class="mt-4 pt-3 border-t border-surface-100">
                <span class="text-[11px] font-semibold text-surface-500 uppercase tracking-wider block mb-2">
                  Alcance de Permisos ({{ getTotalActions(rol) }} acciones concedidas)
                </span>
                <div class="flex flex-wrap gap-1.5">
                  @for (p of rol.permisos; track p.modulo) {
                    @if (p.acciones.length > 0) {
                      <span class="inline-flex items-center px-2 py-0.5 rounded text-[11px] font-medium bg-surface-100 text-surface-700 border border-surface-200">
                        <span class="font-semibold mr-1">{{ p.modulo }}:</span>
                        <span class="text-primary-700 font-bold">{{ p.acciones.length }}</span>
                      </span>
                    }
                  }
                </div>
              </div>
            </div>

            <!-- Footer Stats -->
            <div class="mt-5 pt-3 border-t border-surface-100 flex items-center justify-between text-xs text-surface-500">
              <div class="flex items-center space-x-1.5 font-medium">
                <span class="material-icons text-[16px] text-surface-400">group</span>
                <span>{{ rol.usuariosCount }} {{ rol.usuariosCount === 1 ? 'usuario asignado' : 'usuarios asignados' }}</span>
              </div>
              <div class="text-[11px] text-surface-400">
                Modificado: {{ rol.fechaActualizacion | date:'dd/MM/yyyy' }}
              </div>
            </div>
          </div>
        } @empty {
          <div class="col-span-2 py-12 text-center bg-white rounded-xl border border-surface-200">
            <span class="material-icons text-surface-300 text-4xl mb-2">security</span>
            <p class="font-medium text-surface-700">No se encontraron roles de seguridad</p>
            <p class="text-xs text-surface-400 mt-1">Cree un nuevo rol con la matriz de permisos granular.</p>
          </div>
        }
      </div>
    </div>
  `
})
export class RolesCardsTableComponent {
  roles = input.required<Rol[]>();
  readonly store = inject(IamStore);

  getTotalActions(rol: Rol): number {
    return rol.permisos.reduce((acc, curr) => acc + curr.acciones.length, 0);
  }

  deleteRol(rol: Rol): void {
    if (rol.usuariosCount > 0) {
      this.store.showToast(`No se puede eliminar: tiene ${rol.usuariosCount} usuarios asignados.`, 'error');
      return;
    }
    if (confirm(`¿Está seguro de eliminar el rol "${rol.nombre}"?`)) {
      this.store.deleteRol(rol.id);
    }
  }
}
