// src/features/empresas/components/ModalNuevaSucursal.vue
﻿<script setup lang="ts">
import { toTypedSchema } from '@vee-validate/zod';
import { useForm } from 'vee-validate';
import { crearSucursalSchema } from '../schema/sucursales.schema';
import type { CrearSucursalRequest } from '../dto/sucursales.dto';

const props = defineProps<{
  isLoading?: boolean;
}>();

const emit = defineEmits<{
  (e: 'close'): void;
  (e: 'submit', payload: CrearSucursalRequest): void;
}>();

const { defineField, handleSubmit, errors } = useForm({
  validationSchema: toTypedSchema(crearSucursalSchema),
});

const [codigo, codigoProps] = defineField('codigo');
const [nombre, nombreProps] = defineField('nombre');

const onSubmit = handleSubmit((values) => {
  emit('submit', { codigo: values.codigo, nombre: values.nombre });
});
</script>

<template>
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm transition-opacity">
    <div class="bg-white rounded-lg shadow-xl w-full max-w-md mx-4 overflow-hidden flex flex-col">
      <!-- Header -->
      <div class="px-5 py-4 border-b border-border flex justify-between items-center bg-surface">
        <h3 class="text-lg font-bold text-slate-800 flex items-center gap-2">
          <span class="material-symbols-outlined text-blue-600 text-[20px]">storefront</span>
          Nueva Sucursal
        </h3>
        <button type="button" @click="emit('close')" class="text-slate-400 hover:text-slate-600 transition-colors cursor-pointer">
          <span class="material-symbols-outlined text-[20px]">close</span>
        </button>
      </div>
      
      <!-- Body -->
      <form @submit.prevent="onSubmit" class="p-5 space-y-4 overflow-y-auto [&::-webkit-scrollbar]:hidden [-ms-overflow-style:none] scrollbar-none">
        <div>
          <label for="codigoSucursal" class="block text-sm font-semibold text-slate-700 mb-1">Código</label>
          <input 
            id="codigoSucursal"
            v-model="codigo"
            v-bind="codigoProps"
            type="text" 
            placeholder="Ej. SUC-01" 
            class="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all text-sm"
          />
          <p v-if="errors.codigo" class="text-red-500 text-xs mt-1">{{ errors.codigo }}</p>
        </div>
        <div>
          <label for="nombreSucursal" class="block text-sm font-semibold text-slate-700 mb-1">Nombre de Sucursal</label>
          <input 
            id="nombreSucursal"
            v-model="nombre"
            v-bind="nombreProps"
            type="text" 
            placeholder="Ej. Sede Principal" 
            class="w-full px-3 py-2 border border-slate-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all text-sm"
          />
          <p v-if="errors.nombre" class="text-red-500 text-xs mt-1">{{ errors.nombre }}</p>
        </div>

        <!-- Campos inertes pendientes de backend -->
        <div class="grid grid-cols-2 gap-4">
          <div>
            <label for="ubicacionSucursal" class="block text-sm font-semibold text-slate-700 mb-1">Ubicación</label>
            <!-- Pendiente de backend -->
            <input 
              id="ubicacionSucursal"
              type="text" 
              placeholder="Ej. Centro" 
              disabled
              class="w-full px-3 py-2 border border-slate-300 rounded-md bg-slate-100 text-slate-400 cursor-not-allowed text-sm"
            />
          </div>
          <div>
            <label for="telefonoSucursal" class="block text-sm font-semibold text-slate-700 mb-1">Teléfono</label>
            <!-- Pendiente de backend -->
            <input 
              id="telefonoSucursal"
              type="text" 
              placeholder="Ej. 0212-5551234" 
              disabled
              class="w-full px-3 py-2 border border-slate-300 rounded-md bg-slate-100 text-slate-400 cursor-not-allowed text-sm"
            />
          </div>
        </div>
        <div>
          <label for="direccionSucursal" class="block text-sm font-semibold text-slate-700 mb-1">Dirección</label>
          <!-- Pendiente de backend -->
          <textarea 
            id="direccionSucursal"
            placeholder="Ej. Av. Principal..." 
            disabled
            rows="2"
            class="w-full px-3 py-2 border border-slate-300 rounded-md bg-slate-100 text-slate-400 cursor-not-allowed text-sm resize-none"
          ></textarea>
        </div>
        
        <!-- Actions -->
        <div class="pt-4 flex justify-end gap-2 border-t border-slate-100 mt-6">
          <button 
            type="button" 
            @click="emit('close')" 
            class="px-4 py-2 border border-slate-300 rounded-md text-sm font-semibold text-slate-700 hover:bg-surface transition-colors cursor-pointer"
          >
            Cancelar
          </button>
          <button 
            type="submit" 
            :disabled="isLoading"
            class="px-4 py-2 bg-blue-600 rounded-md text-sm font-semibold text-white hover:bg-blue-700 transition-colors shadow-sm flex items-center gap-1.5 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <span v-if="isLoading" class="material-symbols-outlined text-[18px] animate-spin">sync</span>
            <span v-else class="material-symbols-outlined text-[18px]">save</span>
            {{ isLoading ? 'Guardando...' : 'Guardar' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

// react-template/extracted/src/components/ModalNuevaSucursal.tsx
import React, { useState } from 'react';
import { Sucursal, Empresa } from '../types';

interface ModalNuevaSucursalProps {
  isOpen: boolean;
  empresa: Empresa | null;
  onClose: () => void;
  onSaveSucursal: (empresaId: string, sucursalData: Omit<Sucursal, 'id'>) => void;
}

export const ModalNuevaSucursal: React.FC<ModalNuevaSucursalProps> = ({
  isOpen,
  empresa,
  onClose,
  onSaveSucursal
}) => {
  const [nombre, setNombre] = useState('');
  const [ubicacion, setUbicacion] = useState('Distrito Capital, VE');
  const [encargado, setEncargado] = useState('');
  const [telefono, setTelefono] = useState('');
  const [direccion, setDireccion] = useState('');
  const [error, setError] = useState('');

  if (!isOpen || !empresa) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!nombre.trim() || !encargado.trim()) {
      setError('Por favor indique el nombre de la sucursal y el encargado.');
      return;
    }

    const nextIndex = empresa.sucursales.length + 1;
    const charCode = String.fromCharCode(64 + nextIndex); // A, B, C, D...
    const numPart = empresa.codigo.replace('EMP-', '');
    const generatedCodigo = `SUC-${numPart}${charCode}`;

    onSaveSucursal(empresa.id, {
      codigo: generatedCodigo,
      nombre: nombre.trim(),
      ubicacion: ubicacion.trim(),
      encargado: encargado.trim(),
      telefono: telefono.trim(),
      direccion: direccion.trim(),
      activo: true
    });

    setNombre('');
    setEncargado('');
    setTelefono('');
    setDireccion('');
    setError('');
    onClose();
  };

  return (
    <div className="fixed inset-0 bg-[#0F172A]/40 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-[480px] border border-[#E2E8F0] overflow-hidden flex flex-col max-h-[90vh] animate-in fade-in zoom-in-95 duration-150">
        <div className="px-6 py-3.5 border-b border-[#E2E8F0] flex justify-between items-center bg-[#F8FAFC]">
          <div>
            <h3 className="text-[16px] font-bold text-[#0b1c30]">Nueva Sucursal / Sede</h3>
            <p className="text-[11px] text-slate-500 font-medium">
              Empresa: <strong className="text-blue-600">{empresa.nombre}</strong> ({empresa.codigo})
            </p>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-700 transition-colors p-1 rounded hover:bg-slate-200/50"
          >
            <span className="material-symbols-outlined text-[18px]">close</span>
          </button>
        </div>

        <div className="p-6 overflow-y-auto flex-1">
          {error && (
            <div className="mb-4 p-2.5 bg-red-50 border border-red-200 rounded text-red-600 text-[12px] flex items-center gap-2">
              <span className="material-symbols-outlined text-[16px]">error</span>
              {error}
            </div>
          )}

          <form id="form-nueva-sucursal" onSubmit={handleSubmit} className="space-y-4">
            <div>
              <label className="block text-[12px] font-semibold text-slate-700 mb-1">
                Nombre de la Sucursal / Depósito <span className="text-red-500">*</span>
              </label>
              <input
                value={nombre}
                onChange={(e) => setNombre(e.target.value)}
                placeholder="Ej. Centro Distribución Valencia"
                className="w-full h-[34px] px-3 text-[13px] border border-slate-300 rounded focus:border-[#004ac6] focus:ring-2 focus:ring-blue-500/20 outline-none bg-white text-slate-900"
                required
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-[12px] font-semibold text-slate-700 mb-1">
                  Ubicación (Estado / Región)
                </label>
                <select
                  value={ubicacion}
                  onChange={(e) => setUbicacion(e.target.value)}
                  className="w-full h-[34px] px-3 text-[13px] border border-slate-300 rounded focus:border-[#004ac6] focus:ring-2 focus:ring-blue-500/20 outline-none bg-white text-slate-900 cursor-pointer"
                >
                  <option value="Distrito Capital, VE">Distrito Capital, VE</option>
                  <option value="Carabobo, VE">Carabobo, VE</option>
                  <option value="Miranda, VE">Miranda, VE</option>
                  <option value="Zulia, VE">Zulia, VE</option>
                  <option value="Lara, VE">Lara, VE</option>
                  <option value="Aragua, VE">Aragua, VE</option>
                  <option value="Anzoátegui, VE">Anzoátegui, VE</option>
                  <option value="Bolívar, VE">Bolívar, VE</option>
                </select>
              </div>

              <div>
                <label className="block text-[12px] font-semibold text-slate-700 mb-1">
                  Encargado / Jefe Sede <span className="text-red-500">*</span>
                </label>
                <input
                  value={encargado}
                  onChange={(e) => setEncargado(e.target.value)}
                  placeholder="Ej. Carlos Mendoza"
                  className="w-full h-[34px] px-3 text-[13px] border border-slate-300 rounded focus:border-[#004ac6] focus:ring-2 focus:ring-blue-500/20 outline-none bg-white text-slate-900"
                  required
                />
              </div>
            </div>

            <div>
              <label className="block text-[12px] font-semibold text-slate-700 mb-1">
                Dirección Detallada
              </label>
              <textarea
                value={direccion}
                onChange={(e) => setDireccion(e.target.value)}
                rows={2}
                placeholder="Zona industrial, calle, galpón o centro comercial..."
                className="w-full px-3 py-1.5 text-[13px] border border-slate-300 rounded focus:border-[#004ac6] focus:ring-2 focus:ring-blue-500/20 outline-none bg-white text-slate-900 resize-none"
              />
            </div>

            <div>
              <label className="block text-[12px] font-semibold text-slate-700 mb-1">
                Teléfono de Contacto Sede
              </label>
              <input
                value={telefono}
                onChange={(e) => setTelefono(e.target.value)}
                placeholder="+58 241 0000000"
                className="w-full h-[34px] px-3 text-[13px] border border-slate-300 rounded focus:border-[#004ac6] focus:ring-2 focus:ring-blue-500/20 outline-none bg-white text-slate-900"
              />
            </div>
          </form>
        </div>

        <div className="px-6 py-3.5 border-t border-[#E2E8F0] bg-[#F8FAFC] flex justify-end gap-2">
          <button
            type="button"
            onClick={onClose}
            className="h-[32px] px-4 bg-white border border-slate-300 rounded text-slate-700 font-medium text-[12px] hover:bg-slate-50 transition-colors"
          >
            Cancelar
          </button>
          <button
            type="submit"
            form="form-nueva-sucursal"
            className="h-[32px] px-4 bg-[#004ac6] text-white rounded font-medium text-[12px] hover:bg-blue-700 transition-colors shadow-sm flex items-center gap-1.5"
          >
            <span className="material-symbols-outlined text-[16px]">add</span>
            Crear Sucursal
          </button>
        </div>
      </div>
    </div>
  );
};
