// template/src/app/pages/iam-page/ui/iam-page.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  OnInit,
  inject
} from '@angular/core';
import { IamStore } from '../../../features/iam/store/iam.store';
import { UsuariosTableComponent } from '../../../features/iam/ui/usuarios-table/usuarios-table.component';
import { RolesCardsTableComponent } from '../../../features/iam/ui/roles-list/roles-cards-table.component';
import { UsuarioFormModalComponent } from '../../../features/iam/ui/usuario-form-modal/usuario-form-modal.component';
import { RolFormModalComponent } from '../../../features/iam/ui/rol-form-modal/rol-form-modal.component';

@Component({
  selector: 'app-iam-page',
  standalone: true,
  imports: [
    UsuariosTableComponent,
    RolesCardsTableComponent,
    UsuarioFormModalComponent,
    RolFormModalComponent
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="p-6 max-w-7xl mx-auto space-y-6 animate-in fade-in duration-200">
      
      <!-- Page Header -->
      <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div class="flex items-center space-x-2">
            <span class="material-icons text-primary-600 text-2xl">admin_panel_settings</span>
            <h1 class="text-2xl font-bold text-surface-900 tracking-tight">
              IAM - Gestión de Identidades y Accesos
            </h1>
          </div>
          <p class="text-xs text-surface-500 mt-1">
            Administre usuarios corporativos, roles organizacionales y matrices de permisos de seguridad RBAC.
          </p>
        </div>

        <div class="flex items-center space-x-3">
          <button
            type="button"
            (click)="store.openCreateRolModal()"
            class="px-3.5 py-2 text-xs font-semibold text-surface-700 bg-white border border-surface-300 rounded-lg hover:bg-surface-50 transition-colors shadow-xs flex items-center cursor-pointer">
            <span class="material-icons text-[18px] mr-1.5 text-surface-500">add_moderator</span>
            Crear Rol
          </button>

          <button
            type="button"
            (click)="store.openCreateUsuarioModal()"
            class="px-4 py-2 text-xs font-semibold text-white bg-primary-600 rounded-lg hover:bg-primary-700 transition-colors shadow-sm flex items-center cursor-pointer">
            <span class="material-icons text-[18px] mr-1.5">person_add</span>
            Nuevo Usuario
          </button>
        </div>
      </div>

      <!-- Stats Overview Cards -->
      <div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
        
        <!-- Total Usuarios -->
        <div class="bg-white p-4 rounded-xl border border-surface-200 shadow-xs flex items-center justify-between">
          <div>
            <span class="text-xs font-medium text-surface-500 uppercase tracking-wider">Total Usuarios</span>
            <div class="text-2xl font-bold text-surface-900 mt-1">{{ store.stats().totalUsuarios }}</div>
            <span class="text-[11px] text-surface-400">En todo el ecosistema</span>
          </div>
          <div class="h-11 w-11 rounded-lg bg-surface-100 text-surface-700 flex items-center justify-center">
            <span class="material-icons text-[24px]">group</span>
          </div>
        </div>

        <!-- Usuarios Activos -->
        <div class="bg-white p-4 rounded-xl border border-surface-200 shadow-xs flex items-center justify-between">
          <div>
            <span class="text-xs font-medium text-surface-500 uppercase tracking-wider">Usuarios Activos</span>
            <div class="text-2xl font-bold text-green-600 mt-1">{{ store.stats().activos }}</div>
            <span class="text-[11px] text-green-700 font-medium">Habilitados para login</span>
          </div>
          <div class="h-11 w-11 rounded-lg bg-green-50 text-green-700 flex items-center justify-center border border-green-200">
            <span class="material-icons text-[24px]">verified</span>
          </div>
        </div>

        <!-- Roles Configurados -->
        <div class="bg-white p-4 rounded-xl border border-surface-200 shadow-xs flex items-center justify-between">
          <div>
            <span class="text-xs font-medium text-surface-500 uppercase tracking-wider">Roles y Políticas</span>
            <div class="text-2xl font-bold text-primary-700 mt-1">{{ store.stats().totalRoles }}</div>
            <span class="text-[11px] text-surface-400">Matrices RBAC activas</span>
          </div>
          <div class="h-11 w-11 rounded-lg bg-primary-50 text-primary-700 flex items-center justify-center border border-primary-100">
            <span class="material-icons text-[24px]">shield</span>
          </div>
        </div>

        <!-- Inactivos o Bloqueados -->
        <div class="bg-white p-4 rounded-xl border border-surface-200 shadow-xs flex items-center justify-between">
          <div>
            <span class="text-xs font-medium text-surface-500 uppercase tracking-wider">Inactivos / Bloq.</span>
            <div class="text-2xl font-bold text-amber-600 mt-1">
              {{ store.stats().inactivos + store.stats().bloqueados }}
            </div>
            <span class="text-[11px] text-surface-400">Sin acceso concurrente</span>
          </div>
          <div class="h-11 w-11 rounded-lg bg-amber-50 text-amber-700 flex items-center justify-center border border-amber-200">
            <span class="material-icons text-[24px]">lock</span>
          </div>
        </div>

      </div>

      <!-- Main Tabs & Filters Card -->
      <div class="bg-white rounded-xl border border-surface-200 shadow-sm overflow-hidden">
        
        <!-- Tab Bar Navigation -->
        <div class="flex items-center justify-between border-b border-surface-200 px-6 pt-3 bg-surface-50/50">
          <div class="flex space-x-6">
            
            <button
              type="button"
              (click)="store.setTab('usuarios')"
              class="pb-3 text-sm font-semibold border-b-2 flex items-center space-x-2 transition-colors cursor-pointer"
              [class.border-primary-600]="store.selectedTab() === 'usuarios'"
              [class.text-primary-600]="store.selectedTab() === 'usuarios'"
              [class.border-transparent]="store.selectedTab() !== 'usuarios'"
              [class.text-surface-500]="store.selectedTab() !== 'usuarios'">
              <span class="material-icons text-[18px]">people</span>
              <span>Usuarios ({{ store.usuarios().length }})</span>
            </button>

            <button
              type="button"
              (click)="store.setTab('roles')"
              class="pb-3 text-sm font-semibold border-b-2 flex items-center space-x-2 transition-colors cursor-pointer"
              [class.border-primary-600]="store.selectedTab() === 'roles'"
              [class.text-primary-600]="store.selectedTab() === 'roles'"
              [class.border-transparent]="store.selectedTab() !== 'roles'"
              [class.text-surface-500]="store.selectedTab() !== 'roles'">
              <span class="material-icons text-[18px]">admin_panel_settings</span>
              <span>Roles y Permisos ({{ store.roles().length }})</span>
            </button>

          </div>
        </div>

        <!-- Filter Bar -->
        <div class="p-4 border-b border-surface-200 bg-surface-50/30 flex flex-col md:flex-row md:items-center justify-between gap-3">
          
          <!-- Search input -->
          <div class="flex-1 max-w-md relative">
            <span class="material-icons absolute left-3 top-2.5 text-[18px] text-surface-400">search</span>
            <input
              type="text"
              [value]="store.searchQuery()"
              (input)="onSearchInput($event)"
              [placeholder]="store.selectedTab() === 'usuarios' ? 'Buscar usuario por nombre, email o empresa...' : 'Buscar rol por nombre o código...'"
              class="w-full pl-9 pr-4 py-2 text-xs border border-surface-300 rounded-lg bg-white focus:ring-2 focus:ring-primary-500 focus:border-primary-500 outline-none placeholder-surface-400" />
            @if (store.searchQuery()) {
              <button
                type="button"
                (click)="store.setSearchQuery('')"
                class="absolute right-2.5 top-2 text-surface-400 hover:text-surface-600">
                <span class="material-icons text-[18px]">clear</span>
              </button>
            }
          </div>

          <!-- Secondary Filters (Only for Usuarios tab) -->
          @if (store.selectedTab() === 'usuarios') {
            <div class="flex items-center space-x-3">
              
              <!-- Filter Rol -->
              <div class="relative">
                <select
                  [value]="store.filtroRol()"
                  (change)="onRolFilterChange($event)"
                  class="pl-3 pr-8 py-2 text-xs border border-surface-300 rounded-lg bg-white focus:ring-2 focus:ring-primary-500 focus:border-primary-500 outline-none appearance-none cursor-pointer text-surface-700">
                  <option value="ALL">Todos los Roles</option>
                  @for (r of store.roles(); track r.id) {
                    <option [value]="r.id">{{ r.nombre }}</option>
                  }
                </select>
                <span class="material-icons absolute right-2.5 top-2.5 text-[16px] text-surface-400 pointer-events-none">expand_more</span>
              </div>

              <!-- Filter Estado -->
              <div class="relative">
                <select
                  [value]="store.filtroEstado()"
                  (change)="onEstadoFilterChange($event)"
                  class="pl-3 pr-8 py-2 text-xs border border-surface-300 rounded-lg bg-white focus:ring-2 focus:ring-primary-500 focus:border-primary-500 outline-none appearance-none cursor-pointer text-surface-700">
                  <option value="ALL">Todos los Estados</option>
                  <option value="ACTIVO">Activos</option>
                  <option value="INACTIVO">Inactivos</option>
                  <option value="BLOQUEADO">Bloqueados</option>
                  <option value="INVITADO">Invitados</option>
                </select>
                <span class="material-icons absolute right-2.5 top-2.5 text-[16px] text-surface-400 pointer-events-none">expand_more</span>
              </div>

            </div>
          }

        </div>

        <!-- Tab Content Body -->
        <div class="p-6">
          @if (store.selectedTab() === 'usuarios') {
            <app-usuarios-table [usuarios]="store.filteredUsuarios()" />
          } @else {
            <app-roles-cards-table [roles]="store.filteredRoles()" />
          }
        </div>

      </div>

      <!-- Modals for Users and Roles -->
      @if (store.isUsuarioModalOpen()) {
        <app-usuario-form-modal />
      }

      @if (store.isRolModalOpen()) {
        <app-rol-form-modal />
      }

      <!-- Floating Toast Notifications -->
      @if (store.toast(); as t) {
        <div
          class="fixed bottom-6 right-6 z-50 flex items-center space-x-3 px-4 py-3 rounded-lg shadow-xl text-xs font-semibold text-white animate-in slide-in-from-bottom-4 duration-200"
          [class]="t.type === 'success' ? 'bg-surface-900 border-l-4 border-green-500' : t.type === 'error' ? 'bg-surface-900 border-l-4 border-red-500' : 'bg-surface-900 border-l-4 border-primary-500'">
          <span class="material-icons text-[18px]"
            [class]="t.type === 'success' ? 'text-green-400' : t.type === 'error' ? 'text-red-400' : 'text-primary-400'">
            {{ t.type === 'success' ? 'check_circle' : t.type === 'error' ? 'error' : 'info' }}
          </span>
          <span>{{ t.text }}</span>
        </div>
      }

    </div>
  `
})
export class IamPageComponent implements OnInit {
  readonly store = inject(IamStore);

  ngOnInit(): void {
    this.store.loadInitialData();
  }

  onSearchInput(event: Event): void {
    const val = (event.target as HTMLInputElement).value;
    this.store.setSearchQuery(val);
  }

  onRolFilterChange(event: Event): void {
    const val = (event.target as HTMLSelectElement).value;
    this.store.setFiltroRol(val);
  }

  onEstadoFilterChange(event: Event): void {
    const val = (event.target as HTMLSelectElement).value;
    this.store.setFiltroEstado(val);
  }
}

// src/features/iam/iam-page.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useIam, ROLES_HARDCODED } from './composables/useIam';
import { useToast } from '@/shared/composables/use-toast';
import IamStats from './components/IamStats.vue';
import UsuariosTable from './components/UsuariosTable.vue';
import ModalUsuario from './components/ModalUsuario.vue';
import type { UsuarioResponse, CrearUsuarioRequest, EstadoUsuario } from './dto/iam.dto';

// ─── Composables ──────────────────────────────────────────────────────────────
const toast = useToast();
const {
  obtenerUsuarios,
  crearUsuario,
  actualizarUsuario,
  cambiarEstadoUsuario,
  eliminarUsuario,
} = useIam();

// ─── Data ─────────────────────────────────────────────────────────────────────
// Roles: array quemado temporal hasta que el backend exponga GET /iam/roles
const roles = ROLES_HARDCODED;
const { data: usuarios, isLoading } = obtenerUsuarios;

// ─── Tabs ─────────────────────────────────────────────────────────────────────
type Tab = 'usuarios' | 'roles';
const activeTab = ref<Tab>('usuarios');

// ─── Search & Filters ─────────────────────────────────────────────────────────
const searchQuery = ref('');
const filtroEstado = ref<string>('ALL');
const filtroRol = ref<string>('ALL');

const filteredUsuarios = computed(() => {
  const q = searchQuery.value.toLowerCase().trim();
  const estado = filtroEstado.value;
  const rolId = filtroRol.value;
  const list = usuarios.value ?? [];

  return list.filter((u) => {
    const matchSearch =
      !q ||
      u.nombreCompleto.toLowerCase().includes(q) ||
      u.email.toLowerCase().includes(q) ||
      u.empresa.toLowerCase().includes(q) ||
      u.rol.toLowerCase().includes(q);
    const matchEstado = estado === 'ALL' || u.estado === estado;
    const matchRol = rolId === 'ALL' || u.rolId === rolId;
    return matchSearch && matchEstado && matchRol;
  });
});

// ─── Modal state ──────────────────────────────────────────────────────────────
const isModalOpen = ref(false);
const usuarioEnEdicion = ref<UsuarioResponse | null>(null);

function abrirModalCrear() {
  usuarioEnEdicion.value = null;
  isModalOpen.value = true;
}

function abrirModalEditar(usuario: UsuarioResponse) {
  usuarioEnEdicion.value = usuario;
  isModalOpen.value = true;
}

function cerrarModal() {
  isModalOpen.value = false;
  usuarioEnEdicion.value = null;
}

// ─── Handlers ─────────────────────────────────────────────────────────────────
async function handleSubmitUsuario(payload: CrearUsuarioRequest) {
  try {
    if (usuarioEnEdicion.value) {
      await actualizarUsuario.mutateAsync({ id: usuarioEnEdicion.value.id, data: payload });
      toast.success('Usuario actualizado correctamente.');
    } else {
      await crearUsuario.mutateAsync(payload);
      toast.success('Usuario creado con éxito.');
    }
    cerrarModal();
  } catch (error: any) {
    toast.error(error?.message ?? 'Error al guardar el usuario.');
  }
}

async function handleCambiarEstado(payload: { id: string; estado: EstadoUsuario }) {
  try {
    await cambiarEstadoUsuario.mutateAsync({ id: payload.id, data: { estado: payload.estado } });
    toast.success('Estado del usuario actualizado.');
  } catch {
    toast.error('No se pudo cambiar el estado del usuario.');
  }
}

async function handleEliminar(id: string) {
  try {
    await eliminarUsuario.mutateAsync(id);
    toast.success('Usuario eliminado correctamente.');
  } catch {
    toast.error('Error al eliminar el usuario.');
  }
}

function handleResetPassword(email: string) {
  toast.success(`Enlace de restablecimiento enviado a ${email}`);
}
</script>

<template>
  <div class="p-6 max-w-7xl mx-auto space-y-6 bg-surface-50 min-h-screen font-sans">

    <!-- ── Modal ─────────────────────────────────────────────────────────── -->
    <ModalUsuario
      v-if="isModalOpen"
      :usuario-en-edicion="usuarioEnEdicion"
      :roles="roles ?? []"
      :is-pending="crearUsuario.isPending.value || actualizarUsuario.isPending.value"
      @close="cerrarModal"
      @submit="handleSubmitUsuario"
    />

    <!-- ── Page Header ────────────────────────────────────────────────────── -->
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
      <div>
        <div class="flex items-center space-x-2">
          <span class="material-symbols-outlined text-primary text-2xl">admin_panel_settings</span>
          <h1 class="text-[20px] font-extrabold text-text-main tracking-tight">
            IAM - Gestión de Identidades y Accesos
          </h1>
        </div>
        <p class="text-xs text-text-muted mt-1">
          Administre usuarios corporativos, roles organizacionales y matrices de permisos de seguridad RBAC.
        </p>
      </div>

      <div class="flex items-center space-x-3">
        <!-- Crear Rol (placeholder) -->
        <button
          type="button"
          class="px-3.5 py-2 text-xs font-semibold text-text-main bg-white border border-border rounded-lg hover:bg-surface-50 transition-colors shadow-xs flex items-center cursor-pointer"
        >
          <span class="material-symbols-outlined text-[18px] mr-1.5 text-text-muted">add_moderator</span>
          Crear Rol
        </button>

        <!-- Nuevo Usuario -->
        <button
          type="button"
          class="px-4 py-2 text-xs font-semibold text-white bg-primary rounded-lg hover:bg-primary-hover transition-colors shadow-sm flex items-center cursor-pointer"
          @click="abrirModalCrear"
        >
          <span class="material-symbols-outlined text-[18px] mr-1.5">person_add</span>
          Nuevo Usuario
        </button>
      </div>
    </div>

    <!-- ── Stats Cards ────────────────────────────────────────────────────── -->
    <IamStats
      :usuarios="usuarios ?? []"
      :roles-count="roles?.length ?? 0"
    />

    <!-- ── Main Panel ─────────────────────────────────────────────────────── -->
    <div class="bg-white rounded-xl border border-border shadow-sm overflow-hidden">

      <!-- Tab Bar -->
      <div class="flex items-center justify-between border-b border-border px-6 pt-3 bg-surface-50/50">
        <div class="flex space-x-6">
          <button
            type="button"
            class="pb-3 text-sm font-semibold border-b-2 flex items-center space-x-2 transition-colors cursor-pointer"
            :class="activeTab === 'usuarios'
              ? 'border-primary text-primary'
              : 'border-transparent text-text-muted hover:text-text-main'"
            @click="activeTab = 'usuarios'; searchQuery = ''"
          >
            <span class="material-symbols-outlined text-[18px]">people</span>
            <span>Usuarios ({{ usuarios?.length ?? 0 }})</span>
          </button>

          <button
            type="button"
            class="pb-3 text-sm font-semibold border-b-2 flex items-center space-x-2 transition-colors cursor-pointer"
            :class="activeTab === 'roles'
              ? 'border-primary text-primary'
              : 'border-transparent text-text-muted hover:text-text-main'"
            @click="activeTab = 'roles'; searchQuery = ''"
          >
            <span class="material-symbols-outlined text-[18px]">admin_panel_settings</span>
            <span>Roles y Permisos ({{ roles.length }})</span>
          </button>
        </div>
      </div>

      <!-- Filter Bar -->
      <div class="p-4 border-b border-border bg-surface-50/30 flex flex-col md:flex-row md:items-center justify-between gap-3">

        <!-- Search -->
        <div class="flex-1 max-w-md relative">
          <span class="material-symbols-outlined absolute left-3 top-2.5 text-[18px] text-text-muted pointer-events-none">search</span>
          <input
            type="text"
            v-model="searchQuery"
            :placeholder="activeTab === 'usuarios'
              ? 'Buscar usuario por nombre, email o empresa...'
              : 'Buscar rol por nombre o código...'"
            class="w-full pl-9 pr-4 py-2 text-xs border border-border rounded-lg bg-white focus:ring-2 focus:ring-primary focus:border-primary outline-none placeholder-text-muted"
          />
          <button
            v-if="searchQuery"
            type="button"
            class="absolute right-2.5 top-2 text-text-muted hover:text-text-main cursor-pointer"
            @click="searchQuery = ''"
          >
            <span class="material-symbols-outlined text-[18px]">clear</span>
          </button>
        </div>

        <!-- Filtros secundarios (solo tab usuarios) -->
        <div v-if="activeTab === 'usuarios'" class="flex items-center space-x-3">

          <!-- Filtro por Rol -->
          <div class="relative">
            <select
              v-model="filtroRol"
              class="pl-3 pr-8 py-2 text-xs border border-border rounded-lg bg-white focus:ring-2 focus:ring-primary focus:border-primary outline-none appearance-none cursor-pointer text-text-main"
            >
              <option value="ALL">Todos los Roles</option>
              <option v-for="rol in roles" :key="rol.id" :value="rol.id">{{ rol.nombre }}</option>
            </select>
            <span class="material-symbols-outlined absolute right-2.5 top-2.5 text-[16px] text-text-muted pointer-events-none">expand_more</span>
          </div>

          <!-- Filtro por Estado -->
          <div class="relative">
            <select
              v-model="filtroEstado"
              class="pl-3 pr-8 py-2 text-xs border border-border rounded-lg bg-white focus:ring-2 focus:ring-primary focus:border-primary outline-none appearance-none cursor-pointer text-text-main"
            >
              <option value="ALL">Todos los Estados</option>
              <option value="ACTIVO">Activos</option>
              <option value="INACTIVO">Inactivos</option>
              <option value="BLOQUEADO">Bloqueados</option>
              <option value="INVITADO">Invitados</option>
            </select>
            <span class="material-symbols-outlined absolute right-2.5 top-2.5 text-[16px] text-text-muted pointer-events-none">expand_more</span>
          </div>

        </div>
      </div>

      <!-- Tab Content -->
      <div class="p-6">

        <!-- Loading -->
        <div v-if="isLoading" class="flex flex-col items-center justify-center py-16 text-text-muted">
          <span class="material-symbols-outlined animate-spin text-[32px] text-primary mb-3">sync</span>
          <p class="text-sm font-medium">Cargando datos IAM...</p>
        </div>

        <!-- Tab: Usuarios -->
        <template v-else-if="activeTab === 'usuarios'">
          <UsuariosTable
            :usuarios="filteredUsuarios"
            @editar="abrirModalEditar"
            @cambiar-estado="handleCambiarEstado"
            @eliminar="handleEliminar"
            @reset-password="handleResetPassword"
          />
        </template>

        <!-- Tab: Roles (placeholder) -->
        <template v-else>
          <div class="flex flex-col items-center justify-center py-16 text-text-muted">
            <span class="material-symbols-outlined text-[40px] mb-3 opacity-30">admin_panel_settings</span>
            <p class="font-medium text-text-main">Gestión de Roles — Próximamente</p>
            <p class="text-xs text-text-muted mt-1">
              La administración de roles y permisos RBAC estará disponible en la siguiente iteración.
            </p>
          </div>
        </template>

      </div>
    </div>

  </div>
</template>
